= Learn Spring Cloud

== Description

This is where I explore Spring Cloud technologies.

== Current modules

=== Stringmaster

A small service with simple string operations.
Exposes a REST API.

=== Numbermaster

A small service with simple number operations.
Exposes a REST API

=== Discover

Eureka server

=== Gateway
Custom gateway.
Routes the stringmaster and numbermaster services.

=== Gateway-Zuul
Zuul gateway.
Routes the stringmaster and numbermaster services.

=== Gateway-spring

Routes the stringmaster and numbermaster services.

==== Routing
If for instance the numbermaster service is running on localhost:8081 then the call http://localhost:8081/numbermaster/square/4 will return 16.
If Gateway is running on localhost:8092 then the call localhost:8092/numbermaster/square/4 will redirect to localhost:8081 and also return 16.
If Gateway-Zuul is running on localhost:8090 then the call localhost:8090/nmaster/numbermaster/square/4 will redirect to localhost:8081 and also return 16.